name: Deploy to Azure

on:
  push:
    branches:
      - main
permissions:
    id-token: write
    contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Confirm Connection
        uses: azure/CLI@v1
        with:
            azcliversion: latest
            inlineScript: |
                az account show